version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp
    ports:
      - "8000:80"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravelapp
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local